stages:
- test
- deploy

test:
  stage: test
  image: node:8
  script:
  - yarn
  - yarn test

deploy:
  stage: deploy
  image: node:8
  script:
  - yarn
  - yarn build
  - cp build/index.html build/200.html # Creating fallback page
  - node_modules/.bin/surge build genar-radio.surge.sh
  variables:
    SURGE_LOGIN: $SURGE_LOGIN
    SURGE_TOKEN: $SURGE_TOKEN
