include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test
  - deploy
  - report

test:
  stage: test
  image: node:20
  before_script:
    - apt-get update
    - apt-get install -y libvips-dev build-essential libglib2.0-dev cmake
  script:
    - export NODE_ENV=test
    - export DEBUG=vitest:*
    - npm install
    - npm run test src/sagas/player/index.spec.ts
    - npm run test src/components/SongView/index.spec.tsx
    - npm run coverage
  artifacts:
    paths:
      - coverage/

deploy:
  stage: deploy
  image: node:20
  before_script:
    - apt-get update
    - apt-get install -y libvips-dev build-essential libglib2.0-dev cmake
  script:
    - npm install
    - npm run build
    - cp dist/index.html dist/200.html # Creating fallback page
    - npm install -g wrangler --unsafe-perm=true
    - wrangler pages deploy ./dist --project-name=deplayer --branch=main
  only:
    - master
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
    REACT_APP_VERSION: $CI_COMMIT_TAG

send-results:
  stage: report
  variables:
    API_KEY: $CODE_PULSE_API_KEY
    CODE_PULSE_API_KEY: $CODE_PULSE_API_KEY
    CODE_PULSE_PROJECT_SLUG: Deplayer
  image:
    name: registry.gitlab.com/gtrias/code_pulse/project-scanner
    entrypoint: [""]
  script:
    - ls /builds/deplayer/deplayer
    - /app/project_scanner --server-url $CODE_URL --plugin v8 --directory /builds/deplayer/deplayer
