include:
  - template: Code-Quality.gitlab-ci.yml

stages:
- test
- deploy
- report

test:
  stage: test
  image: node:20
  script:
  - npm install
  - npm run coverage

deploy:
  stage: deploy
  image: node:20
  script:
  - npm install
  - npm run build
  - cp dist/index.html dist/200.html # Creating fallback page
  - node_modules/.bin/surge --project ./dist --domain deplayer.surge.sh
  - npm install -g wrangler --unsafe-perm=true
  - wrangler pages deploy ./dist --project-name=deplayer --branch=main
  only:
  - tags
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
    SURGE_LOGIN: $SURGE_LOGIN
    SURGE_TOKEN: $SURGE_TOKEN
    PUBLIC_URL: https://deplayer.surge.sh
    REACT_APP_VERSION: $CI_COMMIT_TAG

send-results:
  stage: report
  variables:
    API_KEY: $CODE_PULSE_API_KEY
    CODE_PULSE_API_KEY: $CODE_PULSE_API_KEY
    CODE_PULSE_PROJECT_SLUG: Deplayer
  image:
    name: registry.gitlab.com/gtrias/code_pulse/project-scanner
    entrypoint: [""]
  script:
    - ls /builds/deplayer/deplayer
    - /app/project_scanner --server-url $CODE_URL --plugin v8 --directory /builds/deplayer/deplayer
