stages:
- test
- code_quality
- deploy

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
      paths: [gl-code-quality-report.json]

test:
  stage: test
  image: node:8
  script:
  - yarn
  - yarn test

deploy:
  stage: deploy
  image: node:8
  script:
  - yarn
  - yarn build
  - cp build/index.html build/200.html # Creating fallback page
  - node_modules/.bin/surge build genar-radio.surge.sh
  only:
  - tags
  variables:
    SURGE_LOGIN: $SURGE_LOGIN
    SURGE_TOKEN: $SURGE_TOKEN
    PUBLIC_URL: https://genar-radio.surge.sh
    REACT_APP_VERSION: $CI_COMMIT_TAG
