export const FILL_VISIBLE_SONGS = 'FILL_VISIBLE_SONGS'
export const FILL_VISIBLE_SONGS_FULLFILLED = 'FILL_VISIBLE_SONGS_FULLFILLED'
export const FILL_VISIBLE_SONG = 'FILL_VISIBLE_SONG'
export const FILL_VISIBLE_SONG_FULLFILLED = 'FILL_VISIBLE_SONG_FULLFILLED'

export const GET_COLLECTION = 'GET_COLLECTION'
export const COLLECTION_FETCHED = 'COLLECTION_FETCHED'

export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST'
export const SET_CURRENT_PLAYING = 'SET_CURRENT_PLAYING'

export const START_SEARCH = 'START_SEARCH'
