// App
export const INITIALIZED = 'INITIALIZED'
export const INITIALIZE_SETTINGS = 'INITIALIZE_SETTINGS'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

// Songs
export const FILL_VISIBLE_SONGS = 'FILL_VISIBLE_SONGS'
export const FILL_VISIBLE_SONGS_FULLFILLED = 'FILL_VISIBLE_SONGS_FULLFILLED'
export const FILL_VISIBLE_SONG = 'FILL_VISIBLE_SONG'
export const FILL_VISIBLE_SONG_FULLFILLED = 'FILL_VISIBLE_SONG_FULLFILLED'

// Player
export const VOLUME_SET = 'VOLUME_SET'
export const START_PLAYING = 'START_PLAYING'
export const STOP_PLAYING = 'STOP_PLAYING'
export const PAUSE_PLAYING = 'PAUSE_PLAYING'
export const SET_CURRENT_PLAYING = 'SET_CURRENT_PLAYING'
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
export const PLAY_ALL = 'PLAY_ALL'

// Collection
export const GET_COLLECTION = 'GET_COLLECTION'
export const COLLECTION_FETCHED = 'COLLECTION_FETCHED'
export const ADD_TO_COLLECTION = 'ADD_TO_COLLECTION'
export const REMOVE_FROM_COLLECTION = 'REMOVE_FROM_COLLECTION'
export const REMOVE_FROM_COLLECTION_REJECTED = 'REMOVE_FROM_COLLECTION_REJECTED'
export const RECEIVE_COLLECTION = 'RECEIVE_COLLECTION'
export const DELETE_COLLECTION = 'DELETE_COLLECTION'
export const RECEIVE_COLLECTION_REJECTED = 'RECEIVE_COLLECTION_REJECTED'

// Playlist
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST'
export const ADD_SONGS_TO_PLAYLIST = 'ADD_SONGS_TO_PLAYLIST'
export const SET_COLUMN_SORT = 'SET_COLUMN_SORT'

// Queue
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE'
export const RECEIVE_QUEUE = 'RECEIVE_QUEUE'
export const GET_QUEUE_REJECTED = 'GET_QUEUE_REJECTED'
export const ADD_SONGS_TO_QUEUE = 'ADD_SONGS_TO_QUEUE'
export const PLAY_NEXT = 'PLAY_NEXT'
export const PLAY_PREV = 'PLAY_PREV'
export const CLEAR_QUEUE = 'CLEAR_QUEUE'
export const SHUFFLE = 'SHUFFLE'

// Search
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH'
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const START_SEARCH = 'START_SEARCH'
export const SEARCH_FULLFILLED = 'SEARCH_FULLFILLED'
export const SEARCH_REJECTED = 'SEARCH_REJECTED'
export const PUSH_TO_VIEW = 'PUSH_TO_VIEW'
export const SEARCH_FINISHED = 'SEARCH_FINISHED'
export const RECEIVE_SEARCH_INDEX = 'RECEIVE_SEARCH_INDEX'
export const RECEIVE_SEARCH_INDEX_REJECTED = 'RECEIVE_SEARCH_INDEX_REJECTED'

// Settings
export const SAVE_SETTINGS = 'SAVE_SETTINGS'
export const SETTINGS_SAVED_SUCCESSFULLY = 'SETTINGS_SAVED_SUCCESSFULLY'
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS'
export const GET_SETTINGS_REJECTED = 'GET_SETTINGS_REJECTED'

// Connection
export const SET_ONLINE_CONNECTION = 'SET_ONLINE_CONNECTION'
export const SET_OFFLINE_CONNECTION = 'SET_OFFLINE_CONNECTION'
