// App
export const APP_READY = "APP_READY";
export const INITIALIZE = "INITIALIZE";
export const INITIALIZED = "INITIALIZED";
export const INITIALIZE_SETTINGS = "INITIALIZE_SETTINGS";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_RIGHT_PANEL = "TOGGLE_RIGHT_PANEL";
export const TOGGLE_MINI_QUEUE = "TOGGLE_MINI_QUEUE";
export const TOGGLE_SEARCH_OFF = "TOGGLE_SEARCH_OFF";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_MQL = "SET_MQL";
export const SET_HEIGHT_MQL = "SET_HEIGHT_MQL";
export const SET_BACKGROUND_IMAGE = "SET_BACKGROUND_IMAGE";
export const SHOW_ADD_MEDIA_MODAL = "SHOW_ADD_MEDIA_MODAL";
export const HIDE_ADD_MEDIA_MODAL = "HIDE_ADD_MEDIA_MODAL";
export const START_YOUTUBE_DL_SERVER_SCAN = "START_YOUTUBE_DL_SERVER_SCAN";

// Lyrics
export const FETCH_LYRICS = "FETCH_LYRICS"; // Triggers saga to fetch from API

// Player
export const VOLUME_SET = "VOLUME_SET";
export const START_PLAYING = "START_PLAYING";
export const STOP_PLAYING = "STOP_PLAYING";
export const PAUSE_PLAYING = "PAUSE_PLAYING";
export const SET_CURRENT_PLAYING = "SET_CURRENT_PLAYING";
export const SET_CURRENT_PLAYING_STREAMS = "SET_CURRENT_PLAYING_STREAMS";
export const SET_CURRENT_PLAYING_URL = "SET_CURRENT_PLAYING_URL";
export const SET_CURRENT_TIME = "SET_CURRENT_TIME";
export const PLAY_ALL = "PLAY_ALL";
export const PLAY_ALL_COMPLETED = "PLAY_ALL_COMPLETED"; // New: LiveStore action completed
export const ADD_TO_QUEUE_NEXT_COMPLETED = "ADD_TO_QUEUE_NEXT_COMPLETED"; // New: LiveStore action completed
export const PLAY_ERROR = "PLAY_ERROR";
export const REGISTER_PLAYER_ERROR = "REGISTER_PLAYER_ERROR";
export const HIDE_PLAYER = "HIDE_PLAYER";
export const SHOW_PLAYER = "SHOW_PLAYER";
export const SONG_PLAYED = "SONG_PLAYED";
export const CLEAR_PLAYER_ERRORS = "CLEAR_PLAYER_ERRORS";
export const TOGGLE_FULL_SCREEN = "TOGGLE_FULL_SCREEN";
export const TOGGLE_PLAYING = "TOGGLE_PLAYING";
export const SET_PLAYER_DURATION = "SET_PLAYER_DURATION";
export const SET_PLAYER_PLAYED_SECONDS = "SET_PLAYER_PLAYED_SECONDS";
export const TOGGLE_SPECTRUM = "TOGGLE_SPECTRUM";
export const TOGGLE_VISUALS = "TOGGLE_VISUALS";

// Webtorrent
export const ADD_WEBTORRENT_MEDIA = "ADD_WEBTORRENT_MEDIA";

// Collection
export const ADD_TO_COLLECTION = "ADD_TO_COLLECTION";
export const ADD_MEDIA_TO_LIVESTORE = "ADD_MEDIA_TO_LIVESTORE"; // New: Add media to LiveStore
export const MEDIA_ADDED_TO_LIVESTORE = "MEDIA_ADDED_TO_LIVESTORE"; // New: Media was added to LiveStore
export const REMOVE_FROM_COLLECTION = "REMOVE_FROM_COLLECTION";
export const REMOVE_FROM_COLLECTION_REJECTED =
  "REMOVE_FROM_COLLECTION_REJECTED";
export const REMOVE_FROM_COLLECTION_FULFILLED =
  "REMOVE_FROM_COLLECTION_FULFILLED";
export const RECEIVE_COLLECTION = "RECEIVE_COLLECTION";
export const RECEIVE_COLLECTION_ITEM = "RECEIVE_COLLECTION_ITEM";
export const DELETE_COLLECTION = "DELETE_COLLECTION";
export const EXPORT_COLLECTION = "EXPORT_COLLECTION";
export const EXPORT_COLLECTION_FINISHED = "EXPORT_COLLECTION_FINISHED";
export const EXPORT_COLLECTION_REJECTED = "EXPORT_COLLECTION_REJECTED";
export const IMPORT_COLLECTION = "IMPORT_COLLECTION";
export const IMPORT_COLLECTION_FINISHED = "IMPORT_COLLECTION_FINISHED";
export const IMPORT_COLLECTION_REJECTED = "IMPORT_COLLECTION_REJECTED";
export const RECEIVE_COLLECTION_FINISHED = "RECEIVE_COLLECTION_FINISHED";
export const CLEAR_COLLECTION = "CLEAR_COLLECTION";
export const APPLY_MOST_PLAYED_SORT = "APPLY_MOST_PLAYED_SORT";
export const UPDATE_MEDIA = "UPDATE_MEDIA";
export const SET_COLLECTION_FILTER = "SET_COLLECTION_FILTER";
export const CLEAR_COLLECTION_FILTERS = "CLEAR_COLLECTION_FILTERS";

// Playlist
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const ADD_SONGS_TO_PLAYLIST = "ADD_SONGS_TO_PLAYLIST";
export const SET_COLUMN_SORT = "SET_COLUMN_SORT";
export const SAVE_PLAYLIST = "SAVE_PLAYLIST";
export const GET_PLAYLISTS_REJECTED = "GET_PLAYLISTS_REJECTED";
export const RECEIVE_PLAYLISTS = "RECEIVE_PLAYLISTS";

// Queue
export const ADD_TO_QUEUE = "ADD_TO_QUEUE";
export const REMOVE_FROM_QUEUE = "REMOVE_FROM_QUEUE";
export const ADD_SONGS_TO_QUEUE_BY_ID = "ADD_SONGS_TO_QUEUE_BY_ID";
export const RECEIVE_QUEUE = "RECEIVE_QUEUE";
export const GET_QUEUE_REJECTED = "GET_QUEUE_REJECTED";
export const ADD_SONGS_TO_QUEUE = "ADD_SONGS_TO_QUEUE";
export const PLAY_NEXT = "PLAY_NEXT";
export const PLAY_PREV = "PLAY_PREV";
export const CLEAR_QUEUE = "CLEAR_QUEUE";
export const SHUFFLE = "SHUFFLE";
export const REPEAT = "REPEAT";
export const ADD_TO_QUEUE_NEXT = "ADD_TO_QUEUE_NEXT";
export const ADD_ALBUM_TO_QUEUE = "ADD_ALBUM_TO_QUEUE";

// Search
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const START_SEARCH = "START_SEARCH";
export const SEARCH_REJECTED = "SEARCH_REJECTED";
export const PUSH_TO_VIEW = "PUSH_TO_VIEW";
export const SEARCH_FINISHED = "SEARCH_FINISHED";

// Settings
export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const SETTINGS_SAVED_SUCCESSFULLY = "SETTINGS_SAVED_SUCCESSFULLY";
export const SETTINGS_SAVED_REJECTED = "SETTINGS_SAVED_REJECTED";
export const SETTINGS_SAVED = "SETTINGS_SAVED"; // New: LiveStore action completed
export const SETTINGS_DELETED = "SETTINGS_DELETED"; // New: LiveStore action completed
export const RECEIVE_SETTINGS = "RECEIVE_SETTINGS";
export const RECEIVE_SETTINGS_FINISHED = "RECEIVE_SETTINGS_FINISHED";
export const GET_SETTINGS_REJECTED = "GET_SETTINGS_REJECTED";
export const REMOVE_FROM_SETTINGS_REJECTED = "REMOVE_FROM_SETTINGS_REJECTED";
export const DELETE_SETTINGS = "DELETE_SETTINGS";
export const ADD_PROVIDER = "ADD_PROVIDER";
export const REMOVE_PROVIDER = "REMOVE_PROVIDER";
export const START_SCAN_SOURCES = "START_SCAN_SOURCES";

// Notifications
export const SEND_NOTIFICATION = "SEND_NOTIFICATION";

// Connection
export const SET_ONLINE_CONNECTION = "SET_ONLINE_CONNECTION";
export const SET_OFFLINE_CONNECTION = "SET_OFFLINE_CONNECTION";

// Artist
export const LOAD_ARTIST = "LOAD_ARTIST";
export const RECEIVE_ARTIST_METADATA = "RECEIVE_ARTIST_METADATA";
export const CLEAR_ARTIST_METADATA = "CLEAR_ARTIST_METADATA";

// Store songs in the browser
export const PIN_SONG = "PIN_SONG";
export const UNPIN_SONG = "UNPIN_SONG";
export const PIN_ALBUM = "PIN_ALBUM";
export const UNPIN_ALBUM = "UNPIN_ALBUM";

export const SAVE_COLLECTION_FULLFILLED = "SAVE_COLLECTION_FULLFILLED";
export const SAVE_COLLECTION_FAILED = "SAVE_COLLECTION_FAILED";

// Filesystem
export const START_FILESYSTEM_FILES_PROCESSING =
  "START_FILESYSTEM_FILES_PROCESSING";
export const FILESYSTEM_SONG_LOADED = "FILESYSTEM_SONG_LOADED";

// Smart Playlists
export const SAVE_SMART_PLAYLIST = "SAVE_SMART_PLAYLIST";
export const RECEIVE_SMART_PLAYLISTS = "RECEIVE_SMART_PLAYLISTS";
export const DELETE_SMART_PLAYLIST = "DELETE_SMART_PLAYLIST";
export const GET_SMART_PLAYLISTS_REJECTED = "GET_SMART_PLAYLISTS_REJECTED";

// Peers management
export const JOIN_PEER_ROOM = "JOIN_PEER_ROOM";
export const PEER_ERROR = "PEER_ERROR";
export const PEER_INITIALIZATION_FAILED = "PEER_INITIALIZATION_FAILED";
export const UPDATE_PEER_STATUS = "UPDATE_PEER_STATUS";
export const PEER_JOINED = "PEER_JOINED";
export const PEER_LEFT = "PEER_LEFT";
export const RESET_PEER_STATUS = "RESET_PEER_STATUS";
export const PEER_SET_USERNAME = "PEER_SET_USERNAME";

export const SET_ROOMS = "SET_ROOMS";
export const ADD_ROOM = "ADD_ROOM";
export const REMOVE_ROOM = "REMOVE_ROOM";
export const REQUEST_REALTIME_STREAM = "REQUEST_REALTIME_STREAM";

export const START_PROVIDER_SYNC = "START_PROVIDER_SYNC";
export const PROVIDER_SYNC_FINISHED = "PROVIDER_SYNC_FINISHED";
export const PROVIDER_SYNC_FAILED = "PROVIDER_SYNC_FAILED";

export const SET_STREAMING_PEER = "SET_STREAMING_PEER";
export const SET_HOST_STREAMING_STATUS = "SET_HOST_STREAMING_STATUS";
export const JOIN_ROOM_REQUESTED = "JOIN_ROOM_REQUESTED";
export const LEAVE_ROOM_REQUESTED = "LEAVE_ROOM_REQUESTED";
export const PEER_STATUS_RECEIVED = "PEER_STATUS_RECEIVED";
export const JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS";
export const JOIN_ROOM_FAILED = "JOIN_ROOM_FAILED";
export const LEAVE_ROOM_SUCCESS = "LEAVE_ROOM_SUCCESS";
export const LEAVE_ROOM_FAILED = "LEAVE_ROOM_FAILED";
export const SET_PEER_CURRENT_PLAYING = "SET_PEER_CURRENT_PLAYING";

export const REQUEST_SONG_FILE = "REQUEST_SONG_FILE";
export const NOTIFY_CURRENT_PLAYING_TO_ROOM = "NOTIFY_CURRENT_PLAYING_TO_ROOM";
export const SET_PEER_STREAMING = "SET_PEER_STREAMING";

export const FETCH_RECENT_ALBUMS_SUCCESS = "FETCH_RECENT_ALBUMS_SUCCESS";
export const FETCH_RECENT_ALBUMS_ERROR = "FETCH_RECENT_ALBUMS_ERROR";

// Sync
export const SET_SYNC_STATUS = "SET_SYNC_STATUS";
