import classNames from 'classnames'

import Button from '../common/Button'
import Icon from '../common/Icon'
import FormSchema from './FormSchema'

const settingsCard = classNames(
  'card',
  'bg-base-600',
  'shadow-xl',
  'p-6',
  'relative',
  'bg-base-200',
  'p-8',
  'mb-6',
  'rounded-lg',
  'shadow-sm'
)

type ProviderFormProps = {
  providerKey: string,
  settings: any, // LiveStore settings object
  settingsForm: any, // Form schema generated by SettingsBuilder
  onRemove: (providerKey: string) => void
}

interface RemoveProviderBtnProps {
  providerKey: string;
  onRemove: (providerKey: string) => void;
}

const ProviderForm = (props: ProviderFormProps) => {
  const RemoveProviderBtn = ({ providerKey, onRemove }: RemoveProviderBtnProps) => {
    const onClick = () => {
      onRemove(providerKey)
    }

    return (
      <Button
        transparent
        size='lg'
        className='hover:text-error'
        onClick={onClick}
        title={providerKey}
      >
        <Icon icon='faTrash' />
      </Button>
    )
  }

  // Get all instances of this provider type from the actual settings
  const providerInstances = Object.keys(props.settings.providers || {})
    .filter(key => key.startsWith(props.providerKey))

  // Only render forms for providers that exist in both settings and form schema
  const validInstances = providerInstances.filter(
    key => props.settingsForm.providers[key]
  )

  return (
    <>
      {validInstances.map(instanceKey => (
        <div key={instanceKey} className={`${settingsCard} w-full`}>
          <div className='top-2 right-2 absolute'>
            <RemoveProviderBtn
              providerKey={instanceKey}
              onRemove={props.onRemove}
            />
          </div>

          <FormSchema 
            providerKey={instanceKey} 
            schema={props.settingsForm.providers[instanceKey]} 
          />
        </div>
      ))}
    </>
  )
}

export default ProviderForm
