name: Deploy to Skynet

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Build webapp
        run: yarn build
        env:
          REACT_APP_VERSION: ${{ env.GITHUB_REF_NAME }}

      - name: Fix route resolving
        run: cp build/index.html build/404.html

      - name: Deploy to Skynet
        uses: SkynetLabs/deploy-to-skynet-action@v2

        with:
          upload-dir: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.REGISTRY_SECRET }}
          try-files:
          - 'index.html'
          - '/index.html'

