name: Deploy to Skynet

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Build webapp
        run: yarn build
        env:
          PUBLIC_URL: 'https://cg0d9me6o1il37s37fgc7j4v8vchvo1o5k9659no3urbl784ml1mdao.siasky.net/'

      - name: Deploy to Skynet
        uses: SkynetLabs/deploy-to-skynet-action@v2

        with:
          upload-dir: public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && secrets.REGISTRY_SEED || '' }}

